# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\x1a\n\x0cHelloRequest\x12\n\n\x02id\x18\x01 \x01(\t\",\n\nGraphReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\x0c\"#\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\".\n\x10\x41llProductsReply\x12\x1a\n\x08products\x18\x01 \x03(\x0b\x32\x08.Product2r\n\nStatistics\x12.\n\x10Get_Prices_Graph\x12\r.HelloRequest\x1a\x0b.GraphReply\x12\x34\n\x10Get_all_products\x12\r.HelloRequest\x1a\x11.AllProductsReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=17
  _globals['_HELLOREQUEST']._serialized_end=43
  _globals['_GRAPHREPLY']._serialized_start=45
  _globals['_GRAPHREPLY']._serialized_end=89
  _globals['_PRODUCT']._serialized_start=91
  _globals['_PRODUCT']._serialized_end=126
  _globals['_ALLPRODUCTSREPLY']._serialized_start=128
  _globals['_ALLPRODUCTSREPLY']._serialized_end=174
  _globals['_STATISTICS']._serialized_start=176
  _globals['_STATISTICS']._serialized_end=290
# @@protoc_insertion_point(module_scope)
