deployment:
  name: web-frontend
  replicas: 1
  image: rsocontainerregistry.azurecr.io/web-service:latest
  port: 8501
  env:
    - name: WEATHER_API_KEY
      value: "bfb8dccd0b442d975ff062d1f67e9ec8"
    - name: NEWS_API_KEY
      value: "c061ba6443df4b2997b094811d29c11e"
    - name: AUTHENTICATION_URL
      value: "http://web-auth:8000/web-auth"
    - name: INVENTORY_URL
      value: "http://inventory:3000/inventory/graphql"

service:
  name: web-frontend
  port: 8501
  targetPort: 8501
  type: ClusterIP

health:
  initialDelaySeconds: 20
  periodSeconds: 120