apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
      annotations: 
        # This annotation will change on every Helm upgrade, forcing a new rollout
        deployment.kubernetes.io/revision: "{{ .Release.Revision }}"
    spec:
      containers:
      - name: {{ .Values.deployment.name }}
        image: {{ .Values.deployment.image }}
        ports:
        - containerPort: {{ .Values.deployment.port }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.deployment.port }}
          initialDelaySeconds: {{ .Values.health.initialDelaySeconds }}
          periodSeconds: {{ .Values.health.periodSeconds }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.deployment.port }}
          initialDelaySeconds: {{ .Values.health.initialDelaySeconds }}
          periodSeconds: {{ .Values.health.periodSeconds }}
        env:
        {{- range .Values.deployment.env }}
        - name: {{ .name }}
          value: "{{ .value }}"
        {{- end }}
