name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on changes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t galmenase1/web-service:latest .

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: "galmenase1"
          password: "boni4€sogreh"

      # Push Docker image to DockerHub
      - name: Push Docker image
        run: |
          docker push galmenase1/web-service:latest
