name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t rsocontainerregistry.azurecr.io/web-service:latest .

      # Log in to Azure Container Registry using secrets
      - name: Log in to Azure Container Registry
        run: |
          echo "wI0p9nGKlzHZaAGFWjvDIuM9PYpwsnqlnZl/vkG1KD+ACRDgR2Zm" | docker login rsocontainerregistry.azurecr.io --username "rsocontainerregistry" --password-stdin

      # Push Docker image to Azure Container Registry
      - name: Push Docker image to ACR
        run: |
          docker push rsocontainerregistry.azurecr.io/web-service:latest
